"""initial schema

Revision ID: 0001_initial_schema
Revises: 
Create Date: 2026-03-04
"""

# Generated by Alembic
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "0001_initial_schema"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Users
    op.create_table('users',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('email', sa.String(255), unique=True, nullable=False, index=True),
        sa.Column('hashed_password', sa.String(255), nullable=False),
        sa.Column('full_name', sa.String(255), nullable=False),
        sa.Column('role', sa.String(50), nullable=False, server_default='candidate'),
        sa.Column('is_active', sa.Boolean(), server_default=sa.true()),
        sa.Column('is_verified', sa.Boolean(), server_default=sa.false()),
        sa.Column('avatar_url', sa.String(500)),
        sa.Column('last_login', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('clients',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), unique=True),
        sa.Column('company_name', sa.String(255), nullable=False),
        sa.Column('company_size', sa.String(50)),
        sa.Column('industry', sa.String(100)),
        sa.Column('website', sa.String(255)),
        sa.Column('logo_url', sa.String(500)),
        sa.Column('stripe_customer_id', sa.String(255), unique=True),
        sa.Column('subscription_plan', sa.String(50), server_default='free'),
        sa.Column('roles_used_this_month', sa.Integer(), server_default='0'),
        sa.Column('billing_cycle_start', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('candidates',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id', ondelete='CASCADE'), unique=True),
        sa.Column('phone', sa.String(20)),
        sa.Column('location', sa.String(255)),
        sa.Column('years_of_experience', sa.Integer()),
        sa.Column('experience_level', sa.String(50)),
        sa.Column('linkedin_url', sa.String(500)),
        sa.Column('github_url', sa.String(500)),
        sa.Column('portfolio_url', sa.String(500)),
        sa.Column('resume_url', sa.String(500)),
        sa.Column('resume_s3_key', sa.String(500)),
        sa.Column('headline', sa.String(500)),
        sa.Column('bio', sa.Text()),
        sa.Column('skills', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('job_descriptions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id', ondelete='CASCADE'), index=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('original_text', sa.Text(), nullable=False),
        sa.Column('jd_file_url', sa.String(500)),
        sa.Column('jd_s3_key', sa.String(500)),
        sa.Column('status', sa.String(50), server_default='active'),
        sa.Column('required_skills', postgresql.JSONB()),
        sa.Column('preferred_skills', postgresql.JSONB()),
        sa.Column('min_years_experience', sa.Integer()),
        sa.Column('max_years_experience', sa.Integer()),
        sa.Column('seniority_level', sa.String(100)),
        sa.Column('difficulty_level', sa.String(50)),
        sa.Column('parsed_summary', sa.Text()),
        sa.Column('technologies', postgresql.JSONB()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('assessments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('job_description_id', sa.Integer(), sa.ForeignKey('job_descriptions.id', ondelete='CASCADE'), index=True),
        sa.Column('title', sa.String(255), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('status', sa.String(50), server_default='active'),
        sa.Column('has_coding_round', sa.Boolean(), server_default=sa.true()),
        sa.Column('mcq_count', sa.Integer(), server_default='10'),
        sa.Column('coding_count', sa.Integer(), server_default='2'),
        sa.Column('scenario_count', sa.Integer(), server_default='3'),
        sa.Column('time_limit_minutes', sa.Integer(), server_default='90'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('questions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('assessment_id', sa.Integer(), sa.ForeignKey('assessments.id', ondelete='CASCADE'), index=True),
        sa.Column('question_type', sa.String(50), nullable=False),
        sa.Column('question_text', sa.Text(), nullable=False),
        sa.Column('options', postgresql.JSONB()),
        sa.Column('correct_answer', sa.Text()),
        sa.Column('explanation', sa.Text()),
        sa.Column('difficulty', sa.String(50)),
        sa.Column('skills_tested', postgresql.JSONB()),
        sa.Column('max_score', sa.Integer(), server_default='10'),
        sa.Column('order_index', sa.Integer(), server_default='0'),
    )
    op.create_table('test_attempts',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('assessment_id', sa.Integer(), sa.ForeignKey('assessments.id', ondelete='CASCADE'), index=True),
        sa.Column('candidate_id', sa.Integer(), sa.ForeignKey('candidates.id', ondelete='CASCADE'), index=True),
        sa.Column('job_description_id', sa.Integer(), sa.ForeignKey('job_descriptions.id'), index=True),
        sa.Column('token', sa.String(255), unique=True, index=True),
        sa.Column('token_expires_at', sa.DateTime(timezone=True)),
        sa.Column('status', sa.String(50), server_default='invited'),
        sa.Column('started_at', sa.DateTime(timezone=True)),
        sa.Column('submitted_at', sa.DateTime(timezone=True)),
        sa.Column('answers', postgresql.JSONB()),
        sa.Column('total_score', sa.Float()),
        sa.Column('technical_score', sa.Float()),
        sa.Column('coding_score', sa.Float()),
        sa.Column('problem_solving_score', sa.Float()),
        sa.Column('rating_badge', sa.String(50)),
        sa.Column('is_qualified', sa.Boolean(), server_default=sa.false()),
        sa.Column('score_breakdown', postgresql.JSONB()),
        sa.Column('ai_feedback', sa.Text()),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('scored_at', sa.DateTime(timezone=True)),
    )
    op.create_table('subscriptions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id', ondelete='CASCADE'), index=True),
        sa.Column('stripe_subscription_id', sa.String(255), unique=True),
        sa.Column('stripe_price_id', sa.String(255)),
        sa.Column('plan', sa.String(50)),
        sa.Column('status', sa.String(50)),
        sa.Column('current_period_start', sa.DateTime(timezone=True)),
        sa.Column('current_period_end', sa.DateTime(timezone=True)),
        sa.Column('cancel_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('payments',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('subscription_id', sa.Integer(), sa.ForeignKey('subscriptions.id')),
        sa.Column('client_id', sa.Integer(), sa.ForeignKey('clients.id'), index=True),
        sa.Column('stripe_invoice_id', sa.String(255), unique=True),
        sa.Column('stripe_payment_intent_id', sa.String(255)),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('currency', sa.String(10), server_default='usd'),
        sa.Column('status', sa.String(50)),
        sa.Column('paid_at', sa.DateTime(timezone=True)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('platform_settings',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('key', sa.String(255), unique=True, nullable=False, index=True),
        sa.Column('value', sa.Text(), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('category', sa.String(100), server_default='general'),
        sa.Column('is_editable', sa.Boolean(), server_default=sa.true()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        sa.Column('updated_by', sa.Integer(), sa.ForeignKey('users.id')),
    )
    op.create_table('email_templates',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('slug', sa.String(100), unique=True, nullable=False),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('subject', sa.String(500), nullable=False),
        sa.Column('html_body', sa.Text(), nullable=False),
        sa.Column('text_body', sa.Text()),
        sa.Column('variables', postgresql.JSONB()),
        sa.Column('is_active', sa.Boolean(), server_default=sa.true()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('scoring_weights',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(100), server_default='default'),
        sa.Column('technical_weight', sa.Float(), server_default='0.40'),
        sa.Column('coding_weight', sa.Float(), server_default='0.40'),
        sa.Column('problem_solving_weight', sa.Float(), server_default='0.20'),
        sa.Column('qualification_threshold', sa.Float(), server_default='60.0'),
        sa.Column('is_default', sa.Boolean(), server_default=sa.false()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('feature_flags',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('flag_name', sa.String(100), unique=True, nullable=False),
        sa.Column('is_enabled', sa.Boolean(), server_default=sa.false()),
        sa.Column('description', sa.Text()),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('role_templates',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(255), nullable=False),
        sa.Column('description', sa.Text()),
        sa.Column('default_skills', postgresql.JSONB()),
        sa.Column('mcq_count', sa.Integer(), server_default='10'),
        sa.Column('coding_count', sa.Integer(), server_default='2'),
        sa.Column('scenario_count', sa.Integer(), server_default='3'),
        sa.Column('time_limit_minutes', sa.Integer(), server_default='90'),
        sa.Column('has_coding_round', sa.Boolean(), server_default=sa.true()),
        sa.Column('difficulty', sa.String(50), server_default='intermediate'),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )
    op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('users.id')),
        sa.Column('action', sa.String(255), nullable=False),
        sa.Column('resource_type', sa.String(100)),
        sa.Column('resource_id', sa.String(100)),
        sa.Column('details', postgresql.JSONB()),
        sa.Column('ip_address', sa.String(50)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
    )


def downgrade() -> None:
    op.drop_table('audit_logs')
    op.drop_table('role_templates')
    op.drop_table('feature_flags')
    op.drop_table('scoring_weights')
    op.drop_table('email_templates')
    op.drop_table('platform_settings')
    op.drop_table('payments')
    op.drop_table('subscriptions')
    op.drop_table('test_attempts')
    op.drop_table('questions')
    op.drop_table('assessments')
    op.drop_table('job_descriptions')
    op.drop_table('candidates')
    op.drop_table('clients')
    op.drop_table('users')
