"""Mako template for Alembic migration scripts."""
"""Add missing columns to scoring_weights

Revision ID: 49f543910638
Revises: 0001_initial_schema
Create Date: 2026-03-23 15:09:30.425230
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '49f543910638'
down_revision = '0001_initial_schema'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('assessments', 'has_coding_round',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('assessments', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('assessments', 'coding_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('assessments', 'scenario_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('assessments', 'time_limit_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.alter_column('candidates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_candidates_id'), 'candidates', ['id'], unique=False)
    op.alter_column('clients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('clients', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('clients', 'roles_used_this_month',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('clients_stripe_customer_id_key'), 'clients', type_='unique')
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_stripe_customer_id'), 'clients', ['stripe_customer_id'], unique=True)
    op.alter_column('email_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('email_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_email_templates_id'), 'email_templates', ['id'], unique=False)
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_feature_flags_id'), 'feature_flags', ['id'], unique=False)
    op.alter_column('job_descriptions', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('job_descriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('job_descriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_descriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_job_descriptions_id'), 'job_descriptions', ['id'], unique=False)
    op.alter_column('payments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'usd'::character varying"))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.alter_column('platform_settings', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'general'::character varying"))
    op.alter_column('platform_settings', 'is_editable',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('platform_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_platform_settings_id'), 'platform_settings', ['id'], unique=False)
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('questions', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_questions_id'), 'questions', ['id'], unique=False)
    op.alter_column('role_templates', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('10'))
    op.alter_column('role_templates', 'coding_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('2'))
    op.alter_column('role_templates', 'scenario_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3'))
    op.alter_column('role_templates', 'time_limit_minutes',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('90'))
    op.alter_column('role_templates', 'has_coding_round',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('role_templates', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'intermediate'::character varying"))
    op.alter_column('role_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_role_templates_id'), 'role_templates', ['id'], unique=False)
    op.add_column('scoring_weights', sa.Column('communication_weight', sa.Float(), nullable=False))
    op.add_column('scoring_weights', sa.Column('cultural_fit_weight', sa.Float(), nullable=False))
    op.alter_column('scoring_weights', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_server_default=sa.text("'default'::character varying"))
    op.alter_column('scoring_weights', 'technical_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0.4'::double precision"))
    op.alter_column('scoring_weights', 'qualification_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'60'::double precision"))
    op.alter_column('scoring_weights', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('scoring_weights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_scoring_weights_id'), 'scoring_weights', ['id'], unique=False)
    op.drop_column('scoring_weights', 'coding_weight')
    op.drop_column('scoring_weights', 'problem_solving_weight')
    op.alter_column('subscriptions', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subscriptions', 'stripe_price_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', type_='unique')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_stripe_subscription_id'), 'subscriptions', ['stripe_subscription_id'], unique=True)
    op.add_column('test_attempts', sa.Column('pipeline_stage', sa.String(length=50), nullable=False))
    op.add_column('test_attempts', sa.Column('communication_score', sa.Float(), nullable=True))
    op.add_column('test_attempts', sa.Column('cultural_fit_score', sa.Float(), nullable=True))
    op.alter_column('test_attempts', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_attempts', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_attempts', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('test_attempts', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('test_attempts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'invited'::character varying"))
    op.alter_column('test_attempts', 'is_qualified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('test_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_test_attempts_id'), 'test_attempts', ['id'], unique=False)
    op.drop_column('test_attempts', 'coding_score')
    op.drop_column('test_attempts', 'problem_solving_score')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.add_column('test_attempts', sa.Column('problem_solving_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('test_attempts', sa.Column('coding_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_test_attempts_id'), table_name='test_attempts')
    op.alter_column('test_attempts', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('test_attempts', 'is_qualified',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('test_attempts', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'invited'::character varying"))
    op.alter_column('test_attempts', 'token',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('test_attempts', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_attempts', 'candidate_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_attempts', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('test_attempts', 'cultural_fit_score')
    op.drop_column('test_attempts', 'communication_score')
    op.drop_column('test_attempts', 'pipeline_stage')
    op.drop_index(op.f('ix_subscriptions_stripe_subscription_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_unique_constraint(op.f('subscriptions_stripe_subscription_id_key'), 'subscriptions', ['stripe_subscription_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('subscriptions', 'stripe_price_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('subscriptions', 'stripe_subscription_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('subscriptions', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('scoring_weights', sa.Column('problem_solving_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.2'::double precision"), autoincrement=False, nullable=True))
    op.add_column('scoring_weights', sa.Column('coding_weight', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text("'0.4'::double precision"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_scoring_weights_id'), table_name='scoring_weights')
    op.alter_column('scoring_weights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scoring_weights', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('scoring_weights', 'qualification_threshold',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'60'::double precision"))
    op.alter_column('scoring_weights', 'technical_weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0.4'::double precision"))
    op.alter_column('scoring_weights', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'default'::character varying"))
    op.drop_column('scoring_weights', 'cultural_fit_weight')
    op.drop_column('scoring_weights', 'communication_weight')
    op.drop_index(op.f('ix_role_templates_id'), table_name='role_templates')
    op.alter_column('role_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('role_templates', 'difficulty',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'intermediate'::character varying"))
    op.alter_column('role_templates', 'has_coding_round',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('role_templates', 'time_limit_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('role_templates', 'scenario_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('role_templates', 'coding_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('role_templates', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.drop_index(op.f('ix_questions_id'), table_name='questions')
    op.alter_column('questions', 'order_index',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('questions', 'max_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('questions', 'assessment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_platform_settings_id'), table_name='platform_settings')
    op.alter_column('platform_settings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('platform_settings', 'is_editable',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('platform_settings', 'category',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_server_default=sa.text("'general'::character varying"))
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.alter_column('payments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('payments', 'currency',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'usd'::character varying"))
    op.alter_column('payments', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_job_descriptions_id'), table_name='job_descriptions')
    op.alter_column('job_descriptions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_descriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('job_descriptions', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('job_descriptions', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_feature_flags_id'), table_name='feature_flags')
    op.alter_column('feature_flags', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('feature_flags', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_email_templates_id'), table_name='email_templates')
    op.alter_column('email_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('email_templates', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_clients_stripe_customer_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.create_unique_constraint(op.f('clients_stripe_customer_id_key'), 'clients', ['stripe_customer_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('clients', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('clients', 'roles_used_this_month',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('clients', 'subscription_plan',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'free'::character varying"))
    op.alter_column('clients', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_candidates_id'), table_name='candidates')
    op.alter_column('candidates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('candidates', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.alter_column('assessments', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('assessments', 'time_limit_minutes',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('90'))
    op.alter_column('assessments', 'scenario_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3'))
    op.alter_column('assessments', 'coding_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('2'))
    op.alter_column('assessments', 'mcq_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('10'))
    op.alter_column('assessments', 'has_coding_round',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('assessments', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("'active'::character varying"))
    op.alter_column('assessments', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
