"""Mako template for Alembic migration scripts."""
"""make job_description_id nullable

Revision ID: ab32ca9e7760
Revises: 49f543910638
Create Date: 2026-04-06 16:31:07.765419
"""
from alembic import op
import sqlalchemy as sa


revision = 'ab32ca9e7760'
down_revision = '49f543910638'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessments', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('test_attempts', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_attempts', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('assessments', 'job_description_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
