"""Mako template for Alembic migration scripts."""
"""add_salary_notice_period_to_candidates

Revision ID: b63630bbe98b
Revises: ab32ca9e7760
Create Date: 2026-04-07 13:08:56.520785
"""
from alembic import op
import sqlalchemy as sa


revision = 'b63630bbe98b'
down_revision = 'ab32ca9e7760'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('current_salary', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('expected_salary', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('notice_period_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'notice_period_days')
    op.drop_column('candidates', 'expected_salary')
    op.drop_column('candidates', 'current_salary')
    # ### end Alembic commands ###
